name: prompt_master
description: "A new Flutter project."
publish_to: 'none' # Entferne diese Zeile, wenn du es auf pub.dev veröffentlichen möchtest.

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_neumorphic: ^3.0.0 # Füge Flutter Neumorphic hier hinzu
  percent_indicator: ^4.2.2
  mobile_scanner: ^3.5.2
  email_validator: ^2.0.1
  http: ^1.4.0
  logging: ^1.2.0
  localstorage: ^6.0.0
  shared_preferences: ^2.2.2
  firebase_core: ^3.13.1
  firebase_auth: ^5.5.4
  flutter_web_auth_2:
    git:
      url: https://github.com/ThexXTURBOXx/flutter_web_auth_2.git
      path: flutter_web_auth_2
  js: ^0.6.5
  google_sign_in: ^6.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutterfire_cli: ^1.2.0

flutter:
  uses-material-design: true
